export const STEP_ONE_REQUEST = 'STEP_ONE_REQUEST';
export const STEP_ONE_SUCCESS = 'STEP_ONE_SUCCESS';
export const STEP_ONE_RESET = 'STEP_ONE_RESET';

export const STEP_TWO_REQUEST = 'STEP_TWO_REQUEST';

export const STEP_ONE_SIGNED_MESSAGE = 'STEP_ONE_SIGNED_MESSAGE';
export const STEP_TWO_SIGNED_MESSAGE = 'STEP_TWO_SIGNED_MESSAGE'
